application: philrkuz
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /resume
  static_files: resume.pdf
  upload: resume\.pdf

- url: /about
  static_files: about.html
  upload: about\.html

#static dirs
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

- url: /blog
  static_dir: blogposts

- url: /api
  static_dir: api

- url: /partials
  static_dir: partials

- url: /projects
  static_dir: projects
#404'd
- url: /.*
  script: philrkuz.application
