application: philrkuz
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default


handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /resume
  static_files: static/files/resume.pdf
  upload: static/files/resume.pdf

#static dirs
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img
- url: /thumb
  static_dir: static/img/thumbnails
# - url: /blog
#   static_dir: blogposts

- url: /api
  static_dir: data

- url: /partials
  static_dir: partials

- url: /projs
  static_dir: projects
#404'd
- url: /.*
  script: philrkuz.application
